plugins:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "*.gemspec"

RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 4

RSpec/ExampleLength:
  Max: 10

RSpec/MultipleDescribes:
  Enabled: false

RSpec/BeforeAfterAll:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/IdenticalEqualityAssertion:
  Enabled: false

RSpec/ScatteredLet:
  Enabled: false
